# Generated by Django 5.2.7 on 2026-06-03 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_create_subsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            options={'ordering': ['position']},
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(null=False)),
                ('position', models.PositiveIntegerField(null=False, db_index=True, default=0)),
                ('subsection', models.ForeignKey(null=False, db_index=True, on_delete=django.db.models.deletion.CASCADE, to='models.subsection')),
            ],
        ),
    ]
