# Generated by Django 5.2.7 on 2026-06-03 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_create_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            options={'ordering': ['position']},
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=False, db_index=True, on_delete=django.db.models.deletion.CASCADE, to='models.group')),
                ('position', models.PositiveIntegerField(null=False, db_index=True, default=0)),
            ],
        ),
    ]
