# Generated by Django 5.2.7 on 2026-06-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_create_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
