# Generated by Django 5.2.7 on 2026-07-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_subsection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
