# Generated by Django 6.0.7 on 2026-07-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='guide',
            field=models.TextField(blank=True, null=True),
        ),
    ]
