# Generated by Django 6.0.7 on 2026-07-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_row_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='guide',
            field=models.TextField(blank=True, null=True),
        ),
    ]
