# Generated by Django 6.0.7 on 2026-07-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0016_subsection_guide"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="description",
            field=models.CharField(blank=True),
        ),
    ]
