# Generated by Django 6.0.7 on 2026-08-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_model_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='unit',
            field=models.CharField(blank=True),
        ),
    ]
