# Generated by Django 6.0.7 on 2026-08-17 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0019_field_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_value", models.IntegerField(default=0)),
                ("max_value", models.IntegerField()),
                (
                    "field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="models.field"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("max_value__gt", models.F("min_value"))),
                        name="max_value_greater_than_min_value",
                    )
                ],
            },
        ),
    ]
