# Generated by Django 6.0.7 on 2026-08-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0020_create_field_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name="subsection",
            name="name",
            field=models.CharField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="fieldcolumn",
            index=models.Index(fields=["field", "column"], name="field_column_idx"),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(db_index=True),
        ),
    ]
