# Generated by Django 6.0.7 on 2026-08-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_add_indexes_on_name_field_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='read_only',
            field=models.BooleanField(db_index=True, null=False, default=False),
        ),
    ]
