# Generated by Django 6.0.7 on 2026-08-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_add_indexes_on_name_field_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_summary',
            field=models.BooleanField(default=False),
        ),
    ]
