# Generated by Django 6.0.7 on 2026-08-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_group_is_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='is_summary',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
