# Generated by Django 6.0.7 on 2026-09-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0024_field_read_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="display_type",
            field=models.IntegerField(
                choices=[(1, "Required"), (2, "Not Required"), (3, "Read-Only")],
                db_index=True,
                default=1,
            ),
        ),
        migrations.RunSQL(
            sql=[(
                "UPDATE models_field SET display_type = 3 WHERE id IN (SELECT id FROM models_field WHERE read_only IS True)"
            )],
            reverse_sql=[(
                "UPDATE models_field SET read_only = True WHERE id IN (SELECT id FROM models_field WHERE display_type = 3)"
            )],
        ),
        migrations.RemoveField(
            model_name="field",
            name="read_only",
        ),
    ]
