# Generated by Django 6.0.7 on 2026-09-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0024_field_read_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="required",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
