# Generated by Django 6.0.7 on 2026-09-08 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0024_field_read_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True)),
                ('description', models.CharField(blank=True)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_summary', models.BooleanField(db_index=True, default=False)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.subsection')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='BenefitsRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('benefits_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.benefitsgroup')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='BenefitsField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('cell', models.CharField()),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('unit', models.CharField(blank=True)),
                ('benefits_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.benefitsrow')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
