# Generated by Django 6.0.7 on 2026-09-22 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_benefitsgroup_benefitsrow_benefitsfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsection',
            options={'ordering': ['section__code', 'code']},
        ),
    ]
