# Generated by Django 6.0.7 on 2026-09-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0027_alter_subsection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='guide',
            field=models.TextField(blank=True, null=True),
        ),
    ]
