# Generated by Django 6.0.7 on 2026-10-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0028_group_guide'),
        ('projects', '0008_remove_benefitsvalue_unique_project_benefits_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefitsgroup',
            name='subsection',
        ),
        migrations.RemoveField(
            model_name='benefitsrow',
            name='benefits_group',
        ),
        migrations.DeleteModel(
            name='BenefitsField',
        ),
        migrations.DeleteModel(
            name='BenefitsGroup',
        ),
        migrations.DeleteModel(
            name='BenefitsRow',
        ),
    ]
