# Generated by Django 6.0.7 on 2026-10-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0029_remove_benefitsgroup_subsection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="display_type",
            field=models.IntegerField(
                choices=[(1, "Default"), (2, "Summary"), (3, "Settings")],
                db_index=True,
                default=1,
            ),
        ),
        migrations.RunSQL(
            sql=[(
                "UPDATE models_group SET display_type = 2 WHERE id IN (SELECT id FROM models_group WHERE is_summary IS True)"
            )],
            reverse_sql=[(
                "UPDATE models_group SET is_summary = True WHERE id IN (SELECT id FROM models_group WHERE display_type = 2)"
            )],
        ),
        migrations.RemoveField(
            model_name="group",
            name="is_summary",
        ),
    ]
