[project]
name = "calbc"
version = "0.1.0"
description = ""
authors = [
    {name = "Doc Ritezel",email = "pair+doc@ministryofvelocity.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "xlcalculator @ git+https://github.com/cal-itp/xlcalculator@mov/caltrans-calculations"
]

[tool.poetry]
packages = [{include = "calbc", from = "src"}]


[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
