# Generated by Django 5.2.7 on 2025-10-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_create_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="district",
            field=models.IntegerField(
                choices=[
                    (1, "District 1 - Eureka"),
                    (2, "District 2 - Redding"),
                    (3, "District 3 - Marysville / Sacramento"),
                    (4, "District 4 - Bay Area / Oakland"),
                    (5, "District 5 - Central Coast"),
                    (6, "District 6 - Fresno / Bakersfield"),
                    (7, "District 7 - Los Angeles / Ventura"),
                    (8, "District 8 - San Bernardino / Riverside"),
                    (9, "District 9 - Bishop"),
                    (10, "District 10 - Stockton"),
                    (11, "District 11 - San Diego"),
                    (12, "District 12 - Orange County"),
                ],
                null=False,
            ),
        ),
    ]
