# Generated by Django 5.2.7 on 2025-10-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_create_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="construction_period_length",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="data_direction",
            field=models.IntegerField(
                choices=[(1, "One-Way"), (2, "Two-Way")], default=2
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="district",
            field=models.IntegerField(
                choices=[
                    (1, "District 1 - Eureka"),
                    (2, "District 2 - Redding"),
                    (3, "District 3 - Marysville / Sacramento"),
                    (4, "District 4 - Bay Area / Oakland"),
                    (5, "District 5 - Central Coast"),
                    (6, "District 6 - Fresno / Bakersfield"),
                    (7, "District 7 - Los Angeles / Ventura"),
                    (8, "District 8 - San Bernardino / Riverside"),
                    (9, "District 9 - Bishop"),
                    (10, "District 10 - Stockton"),
                    (11, "District 11 - San Diego"),
                    (12, "District 12 - Orange County"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="location",
            field=models.IntegerField(
                choices=[
                    (1, "Southern California"),
                    (2, "Northern California"),
                    (3, "Rural"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="peak_periods_length",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    (
                        "Highway Capacity Expansion",
                        [
                            ("general_highway", "General Highway"),
                            ("hov_lane_addition", "HOV Lane Addition"),
                            ("hot_lane_addition", "HOT Lane Addition"),
                            ("passing_lane", "Passing Lane"),
                            ("intersection", "Intersection"),
                            ("truck_only_lane", "Truck Only Lane"),
                            ("bypass", "Bypass"),
                            ("queuing", "Queuing"),
                            ("pavement", "Pavement"),
                        ],
                    ),
                    (
                        "Rail or Transit Capacity Expansion",
                        [
                            ("passenger_rail", "Passenger Rail"),
                            ("light_rail", "Light Rail (LRT)"),
                            (
                                "highway_rail_grade_crossing",
                                "Highway-Rail Grade Crossing",
                            ),
                        ],
                    ),
                    (
                        "Highway Operational Improvement",
                        [
                            ("auxiliary_lane", "Auxiliary Lane"),
                            ("freeway_connector", "Freeway Connector"),
                            ("hov_connector", "HOV Connector"),
                            ("hov_drop_ramp", "HOV Drop Ramp"),
                            ("off_ramp_widening", "Off-Ramp Widening"),
                            ("on_ramp_widening", "On-Ramp Widening"),
                            ("hot_lane_conversion", "Hot Lane Conversion"),
                        ],
                    ),
                    (
                        "Transportation Management Systems (TMS)",
                        [
                            ("ramp_metering", "Ramp Metering"),
                            (
                                "ramp_metering_signal_coordination",
                                "Ramp Metering Signal Coordination",
                            ),
                            ("incident_management", "Incident Management"),
                            ("traveler_information", "Traveler Information"),
                            (
                                "arterial_signal_management",
                                "Arterial Signal Management",
                            ),
                            (
                                "transit_vehicle_location",
                                "Transit Vehicle Location (AVL)",
                            ),
                            (
                                "transit_vehicle_signal_priority",
                                "Transit Vehicle Signal Priority",
                            ),
                            ("bus_rapid_transit", "Bus Rapid Transit (BRT)"),
                        ],
                    ),
                ],
                null=True,
            ),
        ),
    ]
