# Generated by Django 5.2.7 on 2026-06-04 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0009_create_value'),
        ('projects', '0002_create_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField()),
                ('field', models.ForeignKey(null=False, db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_value_set', to='models.field')),
                ('project', models.ForeignKey(null=False, db_index=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
