# Generated by Django 5.2.7 on 2025-10-18 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_add_project_district"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(null=False)),
                ("help_text", models.CharField(null=False)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.model",
                        null=False,
                    ),
                ),
            ],
        ),
    ]
