# Generated by Django 5.2.7 on 2025-10-21 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_modelversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="model_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.modelversion",
                null=False,
            ),
        )
    ]
