# Generated by Django 6.0.7 on 2026-08-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0020_create_field_range"),
        ("projects", "0004_project_dates"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="value",
            constraint=models.UniqueConstraint(
                fields=("project", "field"), name="unique_project_field"
            ),
        ),
    ]
