# Generated by Django 5.2.7 on 2025-10-18 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_create_model_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelSectionField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(null=False)),
                ("cell", models.CharField(null=False)),
                ("help_text", models.CharField(null=False)),
                (
                    "model_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.modelsection",
                        null=False,
                    ),
                ),
            ],
        )
    ]
