# Generated by Django 5.2.7 on 2025-10-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_projects_modelversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="url",
            field=models.CharField(null=False),
        )
    ]
