# Generated by Django 5.2.7 on 2025-10-18 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_create_model_section_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(null=False)),
                (
                    "model_section_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.modelsectionfield",
                        null=False,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        null=False,
                    ),
                ),
            ],
        ),
    ]
