# Generated by Django 6.0.7 on 2026-08-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_value_unique_project_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
