# Generated by Django 6.0.7 on 2026-09-22 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_benefitsgroup_benefitsrow_benefitsfield'),
        ('projects', '0006_alter_project_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitsValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benefits_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_benefits_value', to='models.benefitsfield')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'benefits_field'), name='unique_project_benefits_field')],
            },
        ),
    ]
