# Generated by Django 6.0.7 on 2026-10-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_benefitsvalue'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='benefitsvalue',
            name='unique_project_benefits_field',
        ),
        migrations.DeleteModel(
            name='BenefitsValue',
        ),
    ]
