# Generated by Django 6.0.7 on 2026-10-05 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasks_database', '0019_rename_django_task_new_ordering_idx_tasks_db_new_ordering_idx_and_more'),
        ('projects', '0008_remove_benefitsvalue_unique_project_benefits_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_task_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_tasks_database.dbtaskresult')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
