name: Pytest

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: runner
          POSTGRES_DB: cal_bc_development
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.8.22
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Install Playwright
        run: uv run playwright install

      - name: Copy .env.example to .env
        run: |
          cp .env.example .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

      - name: Run tests
        run: uv run manage.py test
