name: Pytest

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
      - uses: abatilo/actions-poetry@v3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-cache-${{ runner.os }}
      - run: bin/download
      - run: poetry install
      - run: poetry run pytest
