name: Ruff

on: [push]

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.8.22
          enable-cache: true

      - name: Check format
        uses: astral-sh/ruff-action@v3
