name: Terraform Plan

on:
  pull_request:
    paths:
      - 'bin/**'
      - 'iac/**'
      - 'src/**'
      - '.dockerignore'
      - '.gcloudignore'
      - '.github/workflows/terraform-plan.yml'
      - '.python-version'
      - 'Dockerfile'
      - 'main.py'
      - 'manage.py'
      - 'pyproject.toml'
      - 'uv.lock'

env:
  SERVICE_ACCOUNT: 'github-actions-service-account@cal-itp-data-infra-staging.iam.gserviceaccount.com'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/473674835135/locations/global/workloadIdentityPools/github-actions/providers/cal-bc'
  PROJECT_ID: 'cal-itp-data-infra-staging'

jobs:
  plan:
    name: Staging
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Authenticate Google Service Account
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Setup GCloud utilities
        uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Formatting
        uses: dflook/terraform-fmt-check@v2
        with:
          path: iac/

      - name: Terraform Validation
        uses: dflook/terraform-validate@v2
        with:
          path: iac/

      - name: Terraform Plan
        uses: dflook/terraform-plan@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add_github_comment: changes-only
          path: iac/
